export { ActivityFormFields, validateActivity, getDefaultActivity } from './ActivityFormFields';
export type { ActivityFormData, ActivityType } from './ActivityFormFields';
export { SlideThumbnail, AddSlideButton } from './SlideThumbnail';
export { VerticalSlideColumn } from './VerticalSlideColumn';
export { SlideArranger } from './SlideArranger';
export { ActivityEditorModal } from './ActivityEditorModal';
export { LandingPage, parsePresentationId } from './LandingPage';
export { PresentationPicker } from './PresentationPicker';
export { AuthProvider, useAuth } from './AuthContext';
export type { User } from './AuthContext';
export { LoginScreen } from './LoginScreen';
export { SettingsPanel } from './SettingsPanel';
export { ActivityLibrary, saveToLibrary } from './ActivityLibrary';
export type { LibraryActivity } from './ActivityLibrary';
export { database } from './firebaseConfig';
